baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'Locations'
pageRef = '/locations'
weight = 40

[[menus.main]]
name = 'Books'
pageRef = '/books'
weight = 50

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
